version: '3.8'

services:
  py-chat-service:
    image: ${DOCKER_IMAGE_NAME:-py-chat-service}
    build: .
    ports:
      - "11114:11114"
    env_file:
      - .env.production
    networks:
      - rbmq-network
      - my_mongoDB_network
      - chat_service_network
    deploy:
      resources:
        limits:
          cpus: '2'
          memory: 2G

networks:
  rbmq-network:
    external: true
  my_mongoDB_network:
    external: true
  chat_service_network:
    external: true
